---
# This workflow will deploy the smtp microservice

name: Deploy smtp

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CF_USERNAME:
        required: true
      CF_PASSWORD:
        required: true
      CF_ORG:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SK_SECRETS_DEV:
        required: true
      SK_SECRETS_TEST:
        required: true
      SK_SECRETS_PROD:
        required: true
  push:
    branches:
      - main
    paths:
      - 'sk-smtp/**'
      - '.github/workflows/deploy-smtp.yaml'

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set SK Secrets
        run: |
          target_env_upper=${{ steps.cf-setup.outputs.target-environment-upper }}
          echo "SK_SECRETS=SK_SECRETS_$target_env_upper" >> $GITHUB_ENV

      - uses: ./.github/actions/setup
        id: sk-setup
        with:
          require-redis: "true"
          require-postgres: "true"
          s3-url: "s3://com.singularkey.gsa/dev/microservice-smtp"
          app-directory: "sk-smtp"
          sk-secrets: ${{ secrets[env.SK_SECRETS] }}
          standard-deployment: "true"
