---
# This workflow will help deploy ALL

name: Deploy ALL connectors 1

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  release:
    types: [released]

jobs:
  base-check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for run-manifest in deploy ALL to finish
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: (run-manifest|run-dbconfigs)
          wait-interval: 20

  deploy-jumio:
    needs: base-check
    uses: ./.github/workflows/deploy-jumio.yaml
    secrets: inherit

  deploy-lexisnexis:
    needs: base-check
    uses: ./.github/workflows/deploy-lexisnexis.yaml
    secrets: inherit

  deploy-mfacontainer:
    needs: base-check
    uses: ./.github/workflows/deploy-mfacontainer.yaml
    secrets: inherit

  deploy-node:
    needs: base-check
    uses: ./.github/workflows/deploy-node.yaml
    secrets: inherit

  deploy-onfido:
    needs: base-check
    uses: ./.github/workflows/deploy-onfido.yaml
    secrets: inherit

  deploy-openid:
    needs: base-check
    uses: ./.github/workflows/deploy-openid.yaml
    secrets: inherit

  deploy-smtp:
    needs: base-check
    uses: ./.github/workflows/deploy-smtp.yaml
    secrets: inherit

  deploy-socure:
    needs: base-check
    uses: ./.github/workflows/deploy-socure.yaml
    secrets: inherit

  deploy-totp:
    needs: base-check
    uses: ./.github/workflows/deploy-totp.yaml
    secrets: inherit

  deploy-transunion:
    needs: base-check
    uses: ./.github/workflows/deploy-transunion.yaml
    secrets: inherit

  deploy-transunion-tloxp:
    needs: base-check
    uses: ./.github/workflows/deploy-transunion-tloxp.yaml
    secrets: inherit

  deploy-userpolicy:
    needs: base-check
    uses: ./.github/workflows/deploy-userpolicy.yaml
    secrets: inherit

  deploy-variables:
    needs: base-check
    uses: ./.github/workflows/deploy-variables.yaml
    secrets: inherit

  deploy-webhook:
    needs: base-check
    uses: ./.github/workflows/deploy-webhook.yaml
    secrets: inherit
