---
# This workflow will help deploy ALL

name: Deploy ALL connectors 0

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  release:
    types: [released]

jobs:
  base-check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for run-manifest in deploy ALL to finish
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: (run-manifest|run-dbconfigs)
          wait-interval: 20

  deploy-authenticid:
    needs: base-check
    uses: ./.github/workflows/deploy-authenticid.yaml
    secrets: inherit

  deploy-challenge:
    needs: base-check
    uses: ./.github/workflows/deploy-challenge.yaml
    secrets: inherit

  deploy-credential:
    needs: base-check
    uses: ./.github/workflows/deploy-credential.yaml
    secrets: inherit

  deploy-devicepolicy:
    needs: base-check
    uses: ./.github/workflows/deploy-devicepolicy.yaml
    secrets: inherit

  deploy-ews:
    needs: base-check
    uses: ./.github/workflows/deploy-ews.yaml
    secrets: inherit

  deploy-fido:
    needs: base-check
    uses: ./.github/workflows/deploy-fido.yaml
    secrets: inherit

  deploy-flow:
    needs: base-check
    uses: ./.github/workflows/deploy-flow.yaml
    secrets: inherit

  deploy-functions:
    needs: base-check
    uses: ./.github/workflows/deploy-functions.yaml
    secrets: inherit

  deploy-http:
    needs: base-check
    uses: ./.github/workflows/deploy-http.yaml
    secrets: inherit

  deploy-iovation:
    needs: base-check
    uses: ./.github/workflows/deploy-iovation.yaml
    secrets: inherit
