---
# This workflow will deploy ALL

name: Deploy ALL base

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  release:
    types: [released]

jobs:
  run-esconfigs:
    uses: ./.github/workflows/run-esconfigs.yaml
    secrets: inherit
  
  run-dbconfigs:
    uses: ./.github/workflows/run-dbconfigs.yaml
    secrets: inherit
  
  run-manifest:
    needs: run-dbconfigs
    uses: ./.github/workflows/run-manifest.yaml
    secrets: inherit

  deploy-api:
    needs: run-manifest
    uses: ./.github/workflows/deploy-api.yaml
    secrets: inherit

  deploy-events:
    needs: [run-manifest, run-esconfigs]
    uses: ./.github/workflows/deploy-events.yaml
    secrets: inherit

  deploy-events-read:
    needs: [run-manifest, run-esconfigs]
    uses: ./.github/workflows/deploy-events-read.yaml
    secrets: inherit

  deploy-analytics:
    needs: [run-manifest, run-esconfigs]
    uses: ./.github/workflows/deploy-analytics.yaml
    secrets: inherit

  deploy-oe:
    needs: run-manifest
    uses: ./.github/workflows/deploy-oe.yaml
    secrets: inherit

  deploy-portal:
    uses: ./.github/workflows/deploy-portal.yaml
    secrets: inherit

  deploy-sdk:
    uses: ./.github/workflows/deploy-sdk.yaml
    secrets: inherit
