---
# This workflow will deploy the analytics microservice

name: Deploy analytics

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'sk-analytics/**'
      - '.github/workflows/deploy-analytics.yaml'
  release:
    types: [released]

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-give-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Set SK Secrets Name
        run: |
          target_env_upper=${{ steps.cf-setup.outputs.target-environment-upper }}
          echo "SK_SECRETS_NAME=SK_SECRETS_$target_env_upper" >> $GITHUB_ENV

      - name: Ensure Redis Available
        run: .cloud-gov/ensure_service_available.sh -c aws-elasticache-redis redis-dev sk-redis

      - name: Ensure Postgres Available
        run: .cloud-gov/ensure_service_available.sh -c aws-rds medium-psql sk-postgres

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Download app file with AWS CLI
        run: aws s3 sync s3://com.singularkey.gsa/dev/microservice-analytics/$(cat sk-analytics/version) sk-analytics

      - name: Check hash
        run: |
          cd sk-analytics
          sha256sum -c hash

      - name: Make Executable
        run: chmod +x sk-analytics/sk-app

      - name: Write SingularKey secrets to CF vars file
        env:
          SK_SECRETS: ${{ secrets[env.SK_SECRETS_NAME] }}
        run: |
          echo "$SK_SECRETS" | jq empty
          echo "---" > vars.yaml
          echo "SK_SECRETS: |" >> vars.yaml
          # sed formats yaml value with proper indentation
          echo "$SK_SECRETS" | sed 's/^/  /' >> vars.yaml

      - name: Deploy application
        run: |
          cd sk-analytics
          cf push --vars-file ../vars.yaml --strategy rolling
