---
# This workflow will run deploy the portal static files

name: Deploy portal

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'sk-portal/**'
      - '.github/workflows/deploy-portal.yaml'

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}
          space-suffix: "-closed"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set SK Secrets
        run: |
          target_env_upper=${{ steps.cf-setup.outputs.target-environment-upper }}
          echo "SK_SECRETS=SK_SECRETS_$target_env_upper" >> $GITHUB_ENV

      - uses: ./.github/actions/setup
        id: sk-setup
        with:
          target-environment: ${{ steps.cf-setup.outputs.target-environment }}
          s3-url: "s3://com.singularkey.gsa/dev/sk-portal"
          app-directory: "sk-portal"
          sk-secrets: "{}"
          disable-executable: "true"

      - name: Deploy application
        run: |
          cd sk-portal
          tar -xf build.tar.gz
          rm build.tar.gz
          # Execute a sed command on all files in the 'build' directory to
          # replace the api endpoint url with the correct one for the environment
          find ./build -type f -execdir sed -i 's/skdevapi/idva-api-${{ steps.cf-setup.outputs.target-environment }}/g' '{}' +
          # replace sdk url
          find ./build -type f -execdir sed -i 's/devsdk\.app\.cloud\.gov/idva-sdk-${{ steps.cf-setup.outputs.target-environment }}\.app\.cloud\.gov/g' '{}' +
          cf push --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }} --strategy rolling
