---
# This workflow will run the esconfigs app initialize elasticsearch

name: Run esconfigs

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'sk-esconfigs/**'
      - '.github/workflows/run-esconfigs.yaml'

jobs:
  deploy:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set SK Secrets
        run: |
          target_env_upper=${{ steps.cf-setup.outputs.target-environment-upper }}
          echo "SK_SECRETS=SK_SECRETS_$target_env_upper" >> $GITHUB_ENV

      - uses: ./.github/actions/setup
        id: sk-setup
        with:
          target-environment: ${{ steps.cf-setup.outputs.target-environment }}
          require-elasticsearch: "true"
          create-required-services: "true"
          s3-url: "s3://com.singularkey.gsa/dev/elasticsearch-configs"
          app-directory: "sk-esconfigs"
          sk-secrets: ${{ secrets[env.SK_SECRETS] }}

      - name: Deploy application
        run: |
          cd sk-esconfigs
          cf push --vars-file vars.yaml --task

      - name: Run esconfigs task
        run: cf run-task sk-esconfigs --name task
