---
# This workflow will run the db configs app to initialize postgres db

name: Run db configs

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'sk-dbconfigs/**'
      - '.github/workflows/run-dbconfigs.yaml'

jobs:
  deploy:
    if: github.repository_owner == '18F'
    name: run-dbconfigs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set SK Secrets
        run: |
          target_env_upper=${{ steps.cf-setup.outputs.target-environment-upper }}
          echo "SK_SECRETS=SK_SECRETS_$target_env_upper" >> $GITHUB_ENV

      - uses: ./.github/actions/setup
        id: sk-setup
        with:
          target-environment: ${{ steps.cf-setup.outputs.target-environment }}
          require-redis: "true"
          require-postgres: "true"
          require-s3: "true"
          create-required-services: "true"
          s3-url: "s3://com.singularkey.gsa/dev/database-configs"
          app-directory: "sk-dbconfigs"
          sk-secrets: ${{ secrets[env.SK_SECRETS] }}

      - name: Deploy application
        run: |
          cd sk-dbconfigs
          cf push --vars-file vars.yaml --task

      - name: Run dbconfigs task
        run: cf run-task sk-dbconfigs --name task
