#This workflow update the hashes for new µservice versions

name: Update Hashes

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Download hash files with AWS CLI
        env:
          AWS_S3_PATH: ${{ secrets.AWS_S3_PATH }}
        run: aws s3 sync --exclude "*" --include "*hash" "s3://$AWS_S3_PATH/dev/" ../s3

      - name: Update Hashes
        run: |
          set -x
          for item in $(jq -r 'keys[]' applications.json)
          do
            current=$(cat "$item/version")
            dir=$(jq -r --arg item "$item" '.[$item].s3dir' applications.json)
            mv "../s3/$dir/$current/hash" "$item/hash"
          done

      - uses: crazy-max/ghaction-import-gpg@v4.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: commit updates
        run: |
          git config --global user.name 'idva-bot'
          git config --global user.email 'idva@gsa.gov'
          git add .
          git commit -am "Update Hashes"
          git push
